spring:
  h2:
    console:
      enabled: true
      path: /h2     # Context path - http://localhost:8080/h2
  datasource:
    url: jdbc:h2:mem:solo     # JDBC URL
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true